name: tello
description: Quick and easy way to connect to a DJI Tello Drone. Using standard Dart packages, the socket is created intuitively and commands are sent easily.
publish_to: 'none'
version: 1.0.1
homepage: https://github.com/mateustoin/DJI-Tello-Dart-Package
repository: https://github.com/mateustoin/DJI-Tello-Dart-Package
issue_tracker: https://github.com/mateustoin/DJI-Tello-Dart-Package/issues
#author: 
#  - Mateus Antonio <mateustoin@gmail.com>
#  - Luiz Ferreira <luizalex1997@gmal.com>

environment:
  sdk: ">=3.3.4 <4.0.0"